version: 2.1

parameters:
  action:
    type: enum
    enum: [hello, goodbye]
    default: hello

jobs:
  build-hello:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run:
          name: Run Hello test
          command: |
            bash src/test_hello.sh

  build-goodbye:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run:
          name: Run Hello test
          command: |
            bash src/test_hello.sh

workflows:
  build-workflow:
    jobs:
      - build-hello
      - build-goodbye:
          requires:
            - build-hello

  conditional-workflow:
    when:
      and: # All must be true to trigger
        - equal: [ hello, << pipeline.parameters.action >> ]

    jobs:
      - build-hello