version: 2.1

jobs:
  build-hello:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run:
          name: Run Hello test
          command: |
            bash src/test_hello.sh

  build-goodbye:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run:
          name: Run Hello test
          command: |
            bash src/test_hello.sh

workflows:
  build-workflow:
    jobs:
      - build-hello
      - build-goodbye:
          requires:
            - build-hello