version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run:
          name: Run test
          command: |
            bash src/test.sh

  build-hello:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run:
          name: Run Hello test
          command: |
            bash src/test_hello.sh

workflows:
  build-workflow:
    jobs:
      - test
      - request-build:
          type: approval
          requires:
            - test
      - build-hello:
          requires:
            - request-build