version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.03
    parallelism: 2
    steps:
      - checkout
      - save_cache:
          key: v1-dependencies-
          paths: ~/cache
#      - run:
#          name: Run Hello test
#          command: |
#            bash src/test_hello.sh
#      - run:
#          name: Run Goodbye test
#          command: |
#            bash src/test_goodbye.sh
      - run: circleci tests glob "**/*.sh" | circleci tests split --split-by=filesize

workflows:
  build-workflow:
    jobs:
      - build