version: 2.1

orbs:
  doctl: digitalocean/cli@1.0.0

workflows:
  install_and_configure_cli:
    jobs:
      - doctl/install_and_initialize_cli:
          context: myContext
          executor: doctl/default
