version: 2.1


jobs:
  test:
    parameters:
      run_test:
        type: boolean
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - when:
          condition:
            equal: [ true, << parameters.run_test >> ]
          steps:
            - run:
                name: Run test
                command: |
                  bash src/test.sh

  build-hello:
    docker:
      - image: cimg/base:2022.03
    environment:
      MY_JOB: hello
    steps:
      - checkout
      - run:
          name: Run Hello test
          command: |
            bash src/test_hello.sh
            MY_JOB="hello"

  build-goodbye:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run:
          name: Run Hello test
          command: |
            bash src/test_hello.sh

workflows:
  build-workflow:
    jobs:
      - build-hello
      - build-goodbye:
          requires:
            - build-hello
      - test:
          run_test: true
  conditional-workflow:
    when:
      and: # All must be true to trigger
        - equal: [ hello, $MY_JOB ]

    jobs:
      - build-hello